language: julia
dist: trusty
os:
- linux
julia:
- 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
  - shards
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_SHARDS_DIR=shards
  - BINARYBUILDER_AUTOMATIC_APPLE=true
  - BINARYBUILDER_USE_CCACHE=true
sudo: required
before_script:
- julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder#master"; Pkg.build()'
script:
- julia build_tarballs.jl
deploy:
  provider: releases
  api-key:
    secure: vT0ejMhbqDDNd4F98w386WuTNWk3ryJi7/+GO41FqSWPpDeFs/XGfCLV5afgCT1ESB9KMoQ0b/0J1kJ0nyK6Lcn5Q9bnQ4wCPVHq9Q2WDciFDKiUJrtZKVl7fIOGOkPiEpyHnUrDzgzOgiofdviU+ohbKKLYkUh5miffnb/2oUTx89UdQgOEdEbRo6lef6KbMuEAJw/Pe9vzAPEBmGzjCmQgNo/2gVjAiHeiLRd8zjvkiGEQ/NB9dekxPCKDEKjOgC/uy3fgAnkd7Qwqx7mSRiqnc01aYFUXQUqCxWJkNOc9jkPkDahdZAeG0WmD2hupye9ed+yAe6zKpTNTlPOJSLFCS6kUZFQeNYf0FKYxWJxtWHuUEZX1FwVHJRdmpFh0sHGvMIvbsXrHEZRW1QGUylD4kAZgBnIv3hq9RCchYaV3UJGsiaeH2caDXl8ygjy0fhcSQYlK0c4quwgPhdzbXhTs6rxqzbwUt9JOi7kTILgCrBY4GQvyKw+GyPj3xhDeFF8H5DDM7vRfq4zSds90dVDq92gQ1oBzylwjbb8M/De/EAW93rdNSfXiOb3IqWBzDyRe10HT/tCBxGLBado2hrGwzglrbIbzc6kfk0eSA2CyX8UTG9c71+ZStlXt5kPV+ATUvcLtJ5B5Uwo1P1TFg/AupR/6IjCv8A0pu0oajhc=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: JuliaIO/x264Builder
    branch: master
